name: opx_certification
description: Managing White Certificates for the energy renovation industry
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.18.1  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  bloc:
  country_code_picker: ^3.0.0
  avatar_glow: ^3.0.1
  image_picker: ^1.0.7
  equatable: ^2.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  loader_overlay: ^4.0.0
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/samsung-opx.png"
  image_path_ios: "assets/images/appstore.png"
  background_color_android: "#1630BF"
  min_sdk_android: 21



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Light.otf
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf


